name: VS Code Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_extension:
        description: 'Test VS Code Extension'
        required: false
        default: 'false'
        type: boolean

jobs:
  vscode-setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup VS Code Environment
      run: |
        echo "🔧 Setting up VS Code compatible environment..."
        
        # Creating .vscode directory якщо does not exist
        mkdir -p .vscode
        
        # Creating базових налаштувань VS Code
        cat > .vscode/settings.json << 'EOF'
        {
          "python.defaultInterpreterPath": "./nimda_env/bin/python",
          "python.terminal.activateEnvironment": true,
          "python.linting.enabled": true,
          "python.linting.flake8Enabled": true,
          "python.formatting.provider": "black",
          "files.associations": {
            "*.md": "markdown"
          },
          "markdown.preview.linkify": true,
          "git.autofetch": true,
          "terminal.integrated.env.linux": {
            "NIMDA_AGENT_PATH": "${workspaceFolder}/nimda_agent_plugin"
          }
        }
        EOF

    - name: Test VS Code Configuration
      run: |
        echo "🧪 Testing VS Code configuration..."
        
        # Перевірка синтаксису JSON files
        for file in .vscode/*.json; do
          if [ -f "$file" ]; then
            echo "Validating $file..."
            python3 -m json.tool "$file" > /dev/null && echo "✅ $file is valid" || echo "❌ $file has errors"
          fi
        done

    - name: Test NIMDA Integration
      run: |
        echo "🤖 Testing NIMDA Agent integration..."
        
        if [ -f "nimda_agent_plugin/run_nimda_agent.py" ]; then
          echo "✅ NIMDA Agent found"
          python3 nimda_agent_plugin/run_nimda_agent.py --command "status" || echo "NIMDA Agent test completed"
        else
          echo "⚠️ NIMDA Agent not found"
        fi
