"""
Setup script for nimda_project_deep_build
Auto-generated by NIMDA Agent
"""

from setuptools import setup, find_packages

setup(
    name="nimda_project_deep_build",
    version="0.1.0",
    description="Project managed by NIMDA Agent",
    author="NIMDA Agent",
    packages=find_packages(),
    install_requires=[
        "requests>=2.28.0",
        "pyyaml>=6.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
